### ISSUE TITLE
I purchased a license, but I receive messages that the license is not active

### ISSUE THREAD

**Issue by DennisKost** [jonathanlermitage/ij-extra-all-plugins-pack-pub#1]
<img width="1053" alt="image" src="https://github.com/user-attachments/assets/2d729235-add5-411c-a080-2e222cbcd770">
<img width="544" alt="image" src="https://github.com/user-attachments/assets/75b504dc-ca03-47c0-bc5a-8e2d38464d6a">

**Comment by jonathanlermitage** [comment]
Hi @DennisKost , can you please:
- go to `Help` > `About` > `Copy and Close,` then paste the product information here
- go to `Help` > `Register`, then paste a screenshot of the window
- go to `Help` > `Show Log in Explorer` then upload the `idea.log` file here (or send me the file at _jonathan.lermitage at gmail.com_ if you don't want to make it public)?  
- go to `File` > `Settings` > `Extra Icons`, and see if there is also a message in red saying no license has been found. The same thing for `File` > `Settings` > `Extra ToolWindow Colorful Icons`.

It will help me to understand why the license is not activated.  
Thanks!

**Comment by jonathanlermitage** [comment]
Hum, I think I reproduced this issue. I disconnected my computer from the Internet, and I observed:
- the Extra Icons features work (no red message saying the license is not valid)
- the Extra ToolWindow Colorful Icons features work as well
- but the Extra IDE Tweaks features don't work, and I see the "No valid Extra Tools Pack license..." message.  

I'm very sorry for that. I will fix this that for the next release, planned for tomorrow.  

If you don't want to wait, and if you're behind a proxy, you can try to play with the Proxy settings (`File` > `Settings` > `Appearance and Behavior` > `System Settings` > `HTTP Proxy`), change some settings then check the connectivity with the Check connection button).  
Again, I'm very sorry for this defect. The license verification code is handled by the IDE and this is not supposed to need Internet. Maybe I check the license too early. Anyway, the Extra Icons and Extra ToolWindow Colorful Icons code is more resilient (it checks for a license after a delay). I will adapt the Extra IDE Tweaks code as well.

**Comment by jonathanlermitage** [comment]
I uploaded the new plugin release to the marketplace. It should be publicly available within two days.  
You can also download it from here: [Extra Tools Pack-2024.6.1.zip](https://github.com/user-attachments/files/16326128/Extra.Tools.Pack-2024.6.1.zip)

**Comment by DennisKost** [comment]
> Hi @DennisKost , can you please:
> 
> * go to `Help` > `About` > `Copy and Close,` then paste the product information here
> * go to `Help` > `Register`, then paste a screenshot of the window
> * go to `Help` > `Show Log in Explorer` then upload the `idea.log` file here (or send me the file at _jonathan.lermitage at gmail.com_ if you don't want to make it public)?
> * go to `File` > `Settings` > `Extra Icons`, and see if there is also a message in red saying no license has been found. The same thing for `File` > `Settings` > `Extra ToolWindow Colorful Icons`.
> 
> It will help me to understand why the license is not activated. Thanks!

About:
JetBrains Rider 2024.1.4
Build #RD-241.18034.76, built on June 23, 2024
Licensed to Dennis Kostin
Subscription is active until March 20, 2025.
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
.NET Core v8.0.1 ARM64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 40000M
Cores: 20
Metal Rendering is ON
Registry:
  debugger.valueTooltipAutoShowOnSelection=true
  ide.experimental.ui=true
  ide.new.project.model.index.case.sensitivity=true
Non-Bundled Plugins:
  Batch Scripts Support (1.0.13)
  com.intellij.resharper.HeapAllocationsViewer (2024.1.0)
  some.awesome (1.15)
  com.nasller.CodeGlancePro (1.8.5)
  PythonCore (241.18034.55)
  org.toml.lang (241.17011.8)
  lermitage.ij.all.pack (2024.5.1)
  com.intellij.plugin.adernov.powershell (2.6.1)
  com.intellij.ml.llm (241.18034.12)
  com.intellij.bigdatatools.core (241.18034.62)
  com.intellij.bigdatatools.kafka (241.14494.158)
  com.github.copilot (1.5.16.6140)
  com.majera.intellij.codereview.gitlab (2024.2.3.241)
  zielu.gittoolbox (500.2.10+233)

<img width="456" alt="image" src="https://github.com/user-attachments/assets/5706fc70-ce47-4967-92a2-71d27c7ee8a3">

**Comment by DennisKost** [comment]
> Hi @DennisKost , can you please:
> 
> * go to `Help` > `About` > `Copy and Close,` then paste the product information here
> * go to `Help` > `Register`, then paste a screenshot of the window
> * go to `Help` > `Show Log in Explorer` then upload the `idea.log` file here (or send me the file at _jonathan.lermitage at gmail.com_ if you don't want to make it public)?
> * go to `File` > `Settings` > `Extra Icons`, and see if there is also a message in red saying no license has been found. The same thing for `File` > `Settings` > `Extra ToolWindow Colorful Icons`.
> 
> It will help me to understand why the license is not activated. Thanks!

Yes exactly. two plugins work, one doesn't

**Comment by jonathanlermitage** [comment]
Thanks for these information 👍  
This should be fixed in release [Extra Tools Pack-2024.6.1.zip](https://github.com/user-attachments/files/16326128/Extra.Tools.Pack-2024.6.1.zip)
