### ISSUE TITLE
Conversion from Extra Icons

### ISSUE THREAD

**Issue by EmanueleMelini** [jonathanlermitage/ij-extra-all-plugins-pack-pub#3]
Just converted from the Extra Icons and Extra ToolWindow plugins and bought the license.
I noticed an error on one icon specifically (because it's one of the most I see), the "directory" icon.

When i had the Extra Icons and Extra ToolWindow plugins the directory icon would be this:
<img width="33" alt="immagine" src="https://github.com/user-attachments/assets/d84e763d-3357-4fea-9e16-26caef09f886">

While now on the Extra Tools Pack the icon is this:
<img width="37" alt="immagine" src="https://github.com/user-attachments/assets/2c4e8cf2-d09f-493a-980b-4267be5de23f">

Searched in the settings something that caused this change and i found these settings:
<img width="663" alt="immagine" src="https://github.com/user-attachments/assets/83798de5-c63f-448c-836b-d622240636f9">

<img width="641" alt="immagine" src="https://github.com/user-attachments/assets/6fc9bea2-3135-4bb8-89cb-c26da8b60009">

I think the right setting that would change this icon is the Extra ToolWIndow one, but it is selected "New UI".

I'll specify that after the uninstall of the Extra Icons and Extra ToolWindow plugins and the installation of Extra Tools Pack, these settings above where selected on "Auto select"

Tried uninstalling and reinstalling the plugin but nothing changed.

Is this an expected behaviour or I have some errors on the installation?

OS: MacOS Sonoma 14.6.1
IDE: IntelliJ IDEA 2024.2.3 (Ultimate Edition), Build #IU-242.23339.11, built on September 25, 2024
Plugin: 2024.10.2

**Comment by jonathanlermitage** [comment]
Hi, I think this is the effect of a feature from Extra IDE Tweaks, which is also part of Extra Tools Pack.  
Can you please go to `File > Settings > Tools > Tools > Extra IDE Tweaks`, or directly `Tools > Extra IDE Tweaks`, then check if "Better Folder Icons" is activated? You may want to deactivate it, then restart your IDE.  
![image](https://github.com/user-attachments/assets/4cf1e9b5-7b63-41d3-923a-d44bb6972987)

I apologize for the inconvenience. This should be deactivated by default. This is be fixed or the next release.

**Comment by EmanueleMelini** [comment]
Hi, deactivating this settings fixes the problem.

Thanks for the fast response.
